Add charset
yeslogic/fontconfig-rs pull request #20
Opened 2022-05-27 09:40 UTC by songww

2022-05-31 01:02 UTC, wezm requested changes
Looks pretty good. Some small things to address. Would be great to get some basic test coverage of `CharSet` if possible.

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +                    FcFontSort,
[FontSet::from_raw](https://github.com/yeslogic/fontconfig-rs/blob/b539b1d1bd164788199519638aa368176d87c6e5/fontconfig/src/lib.rs#L453) requires that the pointer is non-NULL. There are [code paths in FcFontSort](https://github.com/freedesktop/fontconfig/blob/e291fda7d42e5d64379555097a066d9c2c4efce3/src/fcmatch.c#L1311) that can result in a NULL pointer being returned. I think `font_sort` probably need to return `Option<FontSet>` to handle this case or assert that the pointer is non-NULL.

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +                    if trim { 1 } else { 0 }, // Trim font list.
Please use the constants here:

```suggestion
                    if trim { FcTrue } else { FcFalse }, // Trim font list.
```

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +                    self.pat,
[The documentation](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfontsort.html) notes:

> The returned FcFontSet references FcPattern structures which may be shared by the return value from multiple FcFontSort calls, applications must not modify these patterns.

We don't currently prevent mutation of the pattern for example with `add_string`. I wonder if we should clone the pattern and call `FcFontSort` on the clone so that it can't be mutated. This method would change take an immutable reference to `self` as well if that was done.

```rust
     pub fn font_sort(&self, trim: bool) -> FontSet {
        let pat = self.clone();
        ⋮
    }
```

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +    pub fn equals(&self, other: &Self) -> bool {
I'm not sure this is needed since it's just delegating to [the `PartialEq` impl](https://github.com/yeslogic/fontconfig-rs/pull/20/files#diff-9bef896198281e7b154b2f5a31d7c886f0cf04d1c9000b80fae8d2754c715600R662), which can be used directly.

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +        let fcset = unsafe { ffi_dispatch!(LIB, FcCharSetCreate,) };
[This can return a NULL pointer](https://github.com/freedesktop/fontconfig/blob/e291fda7d42e5d64379555097a066d9c2c4efce3/src/fccharset.c#L31) on `malloc` failure. There probably should be an assertion like `Pattern::new`.

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +        assert_eq!(res, FcTrue);
I think `res` is being using incorrectly here. The last argument to `FcCharSetMerge` is a boolean indicating if the set was changed. The return value of `FcCharSetMerge` is what indicated success of failure.

>If changed is not NULL, then it returns whether any new chars from b were added to a. Returns FcFalse on failure, either when a is a constant set or from running out of memory. 

— <https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fccharsetmerge.html>

```suggestion
        let changed = ptr::null_mut();
        let res = unsafe { ffi_dispatch!(LIB, FcCharSetMerge, self.fcset, other.fcset, changed) };
        assert_eq!(res, FcTrue);
```

2022-05-31 01:02 UTC, wezm commented on fontconfig/src/lib.rs
> +        let fcset = unsafe { ffi_dispatch!(LIB, FcCharSetIntersect, self.fcset, other.fcset) };
[This can return a NULL pointer](https://github.com/freedesktop/fontconfig/blob/e291fda7d42e5d64379555097a066d9c2c4efce3/src/fccharset.c#L472). Needs an assertion against that. `subtract` and `union` too.

2022-06-14 14:59 UTC, closed without merging

2022-06-14 23:05 UTC, wezm commented
Hi, did you mean to close this? Sorry I didn't review the last commit you made. I didn't know that you had worked on this PR further as GitHub does not notify unless a comment is made or review requested.

2022-06-15 04:46 UTC, songww commented
Yes, there are big problems here, so I'm going to start over.

2022-06-15 04:49 UTC, wezm commented
Ahh ok 👍