Add a `sort_fonts` function that internally calls `FCFontSort`.
yeslogic/fontconfig-rs pull request #39
Opened 2024-01-16 14:38 UTC by alokedesai

* This PR adds a `sort_fonts` function (which internally calls [`FCFontSort`](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfontsort.html)) and an `add_integer` function  (which internally calls [`FCPatternAddInteger`](https://manpages.ubuntu.com/manpages/focal/man3/FcPatternAdd-Type.3.html)).
* The former is especially useful for font fallback support as the information returned by `list_fonts` does not allow for sorting by closeness or trimming results from the font set if the an earlier font in the list already covers the same unicode range as a given font.

2024-01-16 14:40 UTC, alokedesai commented
Hey @wezm 👋🏽 Thanks for maintaining such a fantastic crate. Would love your thoughts on this and whether this is a change you'd accept. Please let me know if you have any questions on the approach!

2024-01-17 00:35 UTC, wezm requested changes
Overall the changes look good. Some minor tweaks suggested. Also please make sure to run `cargo fmt`.

2024-01-17 00:35 UTC, wezm commented on fontconfig/src/lib.rs
> +/// the list which don't include Unicode coverage not provided by earlier elements in the list are elided.
Might be worth dropping a link to <https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfontsort.html> here.

2024-01-17 00:35 UTC, wezm commented on fontconfig/src/lib.rs
> +        let raw_set = ffi_dispatch!(LIB, FcFontSort, ptr::null_mut(), pattern.pat, trim as c_int /* trim */, ptr::null_mut(), &mut res);
```suggestion
    let mut res = sys::FcResultNoMatch; // FcFontSort always returns a (possibly empty) set so we don't need to check this
    let unicode_coverage = ptr::null_mut();
    let config = ptr::null_mut();
    unsafe {
        let raw_set = ffi_dispatch!(LIB, FcFontSort, config, pattern.pat, trim as FcBool, unicode_coverage, &mut res);```

2024-01-17 14:36 UTC, alokedesai commented
Thanks for the review, PTAL.

2024-01-17 14:37 UTC, alokedesai commented on fontconfig/src/lib.rs
> +/// the list which don't include Unicode coverage not provided by earlier elements in the list are elided.
done.

2024-01-18 00:41 UTC, wezm approved these changes

2024-01-18 00:41 UTC, merged